name 'puppet-module-sudoers'
version '0.1.0'
source 'git://github.com/Ericsson/puppet-module-sudoers.git'
author 'Ericsson'
license 'Apache License, Version 2.0'
summary 'Manages sudoers from PUA data'
description 'Manages sudoers file(s) from PUA data'
project_page 'https://github.com/Ericsson/puppet-module-sudoers'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
